/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.twitter.spark.processor.models;

@org.apache.avro.specific.AvroGenerated
public interface TwitterRecordProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"TwitterRecordProtocol\",\"namespace\":\"com.twitter.spark.processor.models\",\"types\":[{\"type\":\"record\",\"name\":\"TweetRecord\",\"doc\":\"* A Tweet Record\",\"fields\":[{\"name\":\"tweetID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"* ID of the Tweet\"},{\"name\":\"tweetDescription\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* Text Description of the Tweet\",\"default\":null},{\"name\":\"creationDtTm\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* Text Description of the Tweet\",\"default\":null},{\"name\":\"tweetUserID\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* Text Description of the Tweet\",\"default\":null},{\"name\":\"tweetUserName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* Text Description of the Tweet\",\"default\":null},{\"name\":\"tweetUserLocation\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* Text Description of the Tweet\",\"default\":null}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends TwitterRecordProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.twitter.spark.processor.models.TwitterRecordProtocol.PROTOCOL;
  }
}